export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_PROFILE_PICTURE = 'FETCH_USER_PROFILE_PICTURE';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_USER_PROFILE_PICTURE = 'SET_USER_PROFILE_PICTURE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
